import React, { useEffect, useMemo, useState } from "react";
import { CalendarPlus, CheckCircle, LinkSimple, WarningCircle } from "@phosphor-icons/react";
import { cancelZoomClass, connectZoomAccount, createZoomClass, disconnectZoomAccount, joinZoomClass, loadZoomAccount, loadZoomClasses, updateZoomClass } from "./zoomRepository.js";

const when = (value) => new Intl.DateTimeFormat("en-NG", { dateStyle: "full", timeStyle: "short", timeZone: "Africa/Lagos" }).format(new Date(value));
const joinOpen = (item) => Date.now() >= new Date(item.scheduled_start).getTime() - 15 * 60_000 && Date.now() <= new Date(item.scheduled_start).getTime() + (Number(item.duration_minutes) + 60) * 60_000;

export function ZoomClasses({ role, lessons = [], students = [] }) {
  const [classes, setClasses] = useState([]); const [account, setAccount] = useState(null); const [notice, setNotice] = useState(null); const [loading, setLoading] = useState(true); const [editingId, setEditingId] = useState(""); const [form, setForm] = useState({ topic: "", lessonNumber: "", date: "", time: "", durationMinutes: "60", studentIds: [], instructions: "" });
  const isInstructor = role === "instructor";
  const refresh = async () => { try { const values = await Promise.all([loadZoomClasses(), isInstructor ? loadZoomAccount() : Promise.resolve({ account: null })]); setClasses(values[0].classes || []); setAccount(values[1].account); } catch (error) { setNotice({ tone: "error", text: error.message }); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, []);
  const upcoming = useMemo(() => classes.filter((item) => item.status === "upcoming" || item.status === "ongoing"), [classes]);
  const nextClass = useMemo(
    () => [...upcoming].sort((first, second) => new Date(first.scheduled_start) - new Date(second.scheduled_start))[0],
    [upcoming],
  );
  async function connect() { try { const result = await connectZoomAccount(); window.location.assign(result.authorizeUrl); } catch (error) { setNotice({ tone: "error", text: error.message }); } }
  async function disconnect() { if (!window.confirm("Disconnect your Zoom account? Existing classes will remain visible but cannot be updated until you reconnect.")) return; try { await disconnectZoomAccount(); setNotice({ tone: "success", text: "Zoom account disconnected." }); refresh(); } catch (error) { setNotice({ tone: "error", text: error.message }); } }
  async function schedule(event) { event.preventDefault(); try { if (editingId) await updateZoomClass({ ...form, classId: editingId }); else await createZoomClass(form); setEditingId(""); setForm({ topic: "", lessonNumber: "", date: "", time: "", durationMinutes: "60", studentIds: [], instructions: "" }); setNotice({ tone: "success", text: editingId ? "Zoom Class updated." : "Zoom Class scheduled and assigned students can now see it." }); refresh(); } catch (error) { setNotice({ tone: "error", text: error.message }); } }
  function edit(item) { const local = new Date(new Date(item.scheduled_start).getTime() + 60 * 60_000).toISOString(); setEditingId(item.id); setForm({ topic: item.topic, lessonNumber: String(item.lesson_number), date: local.slice(0, 10), time: local.slice(11, 16), durationMinutes: String(item.duration_minutes), studentIds: (item.zoom_class_attendees || []).map((attendee) => attendee.student_id), instructions: item.instructions || "" }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function join(classId) { try { const { joinUrl } = await joinZoomClass(classId); window.open(joinUrl, "_blank", "noopener,noreferrer"); } catch (error) { setNotice({ tone: "error", text: error.message }); } }
  if (loading) return <section className="portal-panel"><p className="portal-muted">Loading Zoom Classes…</p></section>;
  return <section className={`portal-panel zoom-classes${isInstructor ? " zoom-classes--instructor" : " zoom-classes--student"}`}><div className="portal-panel-heading"><div><p>{isInstructor ? "Instructor Zoom" : "Online study"}</p><h2>{isInstructor ? "Zoom Classes" : "Online Classes"}</h2><span>All times are shown in Nigerian local time (WAT).</span></div><CalendarPlus size={34} weight="duotone" /></div>{notice && <div className={notice.tone === "error" ? "portal-inline-message is-error" : "portal-inline-message"}>{notice.tone === "error" ? <WarningCircle size={18} /> : <CheckCircle size={18} />}{notice.text}</div>}
    {!isInstructor && <section className="zoom-student-summary" aria-label="Your online class summary"><article><span><CalendarPlus aria-hidden="true" size={23} weight="duotone" /></span><div><small>Scheduled for you</small><strong>{upcoming.length} {upcoming.length === 1 ? "class" : "classes"}</strong><p>{upcoming.length ? "Keep your study time clear." : "New classes will appear here."}</p></div></article><article><span><CheckCircle aria-hidden="true" size={23} weight="duotone" /></span><div><small>Next session</small><strong>{nextClass?.topic || "No class scheduled"}</strong><p>{nextClass ? when(nextClass.scheduled_start) : "Your instructor will add the next session."}</p></div></article></section>}
    {isInstructor && <div className="zoom-account-card"><div><strong>{account?.connection_status === "connected" ? "Zoom account connected" : "Connect your Zoom account"}</strong><small>{account?.zoom_email || "Connect securely to schedule and manage your own Zoom meetings."}</small></div>{account?.connection_status === "connected" ? <button className="portal-secondary-button" type="button" onClick={disconnect}>Disconnect</button> : <button className="portal-primary-button" type="button" onClick={connect}><LinkSimple size={18} />Connect Zoom Account</button>}</div>}
    {isInstructor && account?.connection_status === "connected" && <form className="zoom-schedule-form" onSubmit={schedule}><h3>{editingId ? "Edit Zoom Class" : "Schedule Zoom Class"}</h3><label>Class title<input required value={form.topic} onChange={(event) => setForm({ ...form, topic: event.target.value })} /></label><label>DBS lesson<select required value={form.lessonNumber} onChange={(event) => setForm({ ...form, lessonNumber: event.target.value })}><option value="">Choose lesson</option>{lessons.map((lesson) => <option value={lesson.number} key={lesson.number}>Lesson {lesson.number}: {lesson.title}</option>)}</select></label><div className="zoom-form-grid"><label>Date (WAT)<input required type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Start time (WAT)<input required type="time" value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })} /></label><label>Duration (minutes)<input required min="15" max="480" type="number" value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: event.target.value })} /></label></div><fieldset><legend>Assign students</legend>{students.length ? students.map((student) => <label key={student.id} className="zoom-attendee"><input type="checkbox" checked={form.studentIds.includes(student.id)} onChange={(event) => setForm({ ...form, studentIds: event.target.checked ? [...form.studentIds, student.id] : form.studentIds.filter((id) => id !== student.id) })} />{student.full_name}</label>) : <span className="portal-muted">You have no assigned students yet.</span>}</fieldset><label>Class instructions (optional)<textarea rows="3" value={form.instructions} onChange={(event) => setForm({ ...form, instructions: event.target.value })} /></label><div className="zoom-class-actions"><button className="portal-primary-button" type="submit">{editingId ? "Save class" : "Schedule Zoom Class"}</button>{editingId && <button className="portal-secondary-button" type="button" onClick={() => { setEditingId(""); setForm({ topic: "", lessonNumber: "", date: "", time: "", durationMinutes: "60", studentIds: [], instructions: "" }); }}>Cancel edit</button>}</div></form>}
    <div className="zoom-class-list"><h3>{isInstructor ? "Your classes" : "Your assigned classes"}</h3>{classes.length ? classes.map((item) => <article key={item.id}><div><span className={`portal-status portal-status--${item.status}`}>{item.status}</span><h3>{item.topic}</h3><p>{item.lessons?.title || `Lesson ${item.lesson_number}`}</p><small>{when(item.scheduled_start)} · {item.duration_minutes} minutes</small>{item.instructions && <p className="portal-muted">{item.instructions}</p>}{!isInstructor && item.instructors?.profiles?.full_name && <small>Instructor: {item.instructors.profiles.full_name}</small>}{isInstructor && <small>{(item.zoom_class_attendees || []).map((attendee) => `${attendee.students?.full_name || "Student"}: ${attendee.attendance_status}`).join(" · ")}</small>}</div><div className="zoom-class-actions">{!isInstructor && <button className="portal-primary-button" disabled={!joinOpen(item) || item.status === "cancelled"} type="button" onClick={() => join(item.id)}>{joinOpen(item) ? "Join Class" : "Available 15 min before"}</button>}{isInstructor && item.status === "upcoming" && <><button className="portal-secondary-button" type="button" onClick={() => edit(item)}>Edit class</button><button className="portal-danger-button" type="button" onClick={() => cancelZoomClass(item.id).then(() => { setNotice({ tone: "success", text: "Zoom Class cancelled." }); refresh(); }).catch((error) => setNotice({ tone: "error", text: error.message }))}>Cancel class</button></>}</div></article>) : <p className="portal-empty">{isInstructor ? "No Zoom Classes scheduled yet." : "You do not have any assigned Online Classes."}</p>}</div></section>;
}
