export const ADMIN_EMAIL = "alvanmos188@yahoo.com";

export const adminSections = [
  { id: "dashboard", label: "Dashboard" },
  { id: "students", label: "Students" },
  { id: "instructors", label: "Instructors" },
  { id: "lessons", label: "Lessons" },
  { id: "questions", label: "Questions" },
  { id: "certificates", label: "Certificates" },
  { id: "reports", label: "Reports" },
  { id: "news", label: "News" },
];

export const initialStudents = [
  {
    id: "student-001",
    serial: "DBS-KD-0001",
    name: "Amina Yusuf",
    denomination: "Seventh-day Adventist",
    status: "Active",
    milestone: "Awaiting Baptism",
    instructorId: "instructor-001",
    progress: 72,
    currentLesson: 19,
    joined: "2026-01-14",
    location: { city: "Kaduna North", lat: 10.5264, lng: 7.4388 },
  },
  {
    id: "student-002",
    serial: "DBS-KD-0002",
    name: "Daniel Okafor",
    denomination: "Pentecostal",
    status: "Active",
    milestone: "Baptized",
    instructorId: "instructor-002",
    progress: 46,
    currentLesson: 12,
    joined: "2026-01-19",
    location: { city: "Barnawa", lat: 10.4705, lng: 7.4272 },
  },
  {
    id: "student-003",
    serial: "DBS-KD-0003",
    name: "Musa Ibrahim",
    denomination: "Non-Adventist",
    status: "Inactive",
    milestone: "Studying",
    instructorId: "instructor-001",
    progress: 23,
    currentLesson: 6,
    joined: "2026-02-03",
    location: { city: "Rigasa", lat: 10.5097, lng: 7.3898 },
  },
  {
    id: "student-004",
    serial: "DBS-KD-0004",
    name: "Grace Audu",
    denomination: "Seventh-day Adventist",
    status: "Active",
    milestone: "Awaiting Graduation",
    instructorId: "instructor-003",
    progress: 96,
    currentLesson: 25,
    joined: "2025-11-22",
    location: { city: "Kawo", lat: 10.5675, lng: 7.4539 },
  },
  {
    id: "student-005",
    serial: "DBS-KD-0005",
    name: "Samuel John",
    denomination: "Catholic",
    status: "Active",
    milestone: "Graduated",
    instructorId: "instructor-003",
    progress: 100,
    currentLesson: 26,
    joined: "2025-09-08",
    location: { city: "Ungwan Rimi", lat: 10.5359, lng: 7.4694 },
  },
  {
    id: "student-006",
    serial: "DBS-KD-0006",
    name: "Ruth Bako",
    denomination: "Baptist",
    status: "Active",
    milestone: "Studying",
    instructorId: null,
    progress: 4,
    currentLesson: 1,
    joined: "2026-06-04",
    location: { city: "Sabon Tasha", lat: 10.4455, lng: 7.4217 },
  },
  {
    id: "student-007",
    serial: "DBS-KD-0007",
    name: "Peter Yakubu",
    denomination: "Non-Adventist",
    status: "Active",
    milestone: "Awaiting Baptism",
    instructorId: "instructor-004",
    progress: 81,
    currentLesson: 21,
    joined: "2025-12-16",
    location: { city: "Malali", lat: 10.5485, lng: 7.4561 },
  },
  {
    id: "student-008",
    serial: "DBS-KD-0008",
    name: "Maryam Sule",
    denomination: "Seventh-day Adventist",
    status: "Inactive",
    milestone: "Studying",
    instructorId: "instructor-002",
    progress: 35,
    currentLesson: 9,
    joined: "2026-02-24",
    location: { city: "Tudun Wada", lat: 10.4988, lng: 7.4301 },
  },
  {
    id: "student-009",
    serial: "DBS-KD-0009",
    name: "Emmanuel Danladi",
    denomination: "Methodist",
    status: "Active",
    milestone: "Baptized",
    instructorId: "instructor-004",
    progress: 61,
    currentLesson: 16,
    joined: "2026-01-08",
    location: { city: "Narayi", lat: 10.4593, lng: 7.4669 },
  },
  {
    id: "student-010",
    serial: "DBS-KD-0010",
    name: "Esther Luka",
    denomination: "Seventh-day Adventist",
    status: "Active",
    milestone: "Graduated",
    instructorId: "instructor-001",
    progress: 100,
    currentLesson: 26,
    joined: "2025-08-12",
    location: { city: "Gonin Gora", lat: 10.4157, lng: 7.3977 },
  },
  {
    id: "student-011",
    serial: "DBS-KD-0011",
    name: "Josephine Mark",
    denomination: "Anglican",
    status: "Active",
    milestone: "Studying",
    instructorId: null,
    progress: 8,
    currentLesson: 2,
    joined: "2026-06-09",
    location: { city: "Mando", lat: 10.6191, lng: 7.3764 },
  },
  {
    id: "student-012",
    serial: "DBS-KD-0012",
    name: "Caleb Sunday",
    denomination: "Non-Adventist",
    status: "Active",
    milestone: "Awaiting Graduation",
    instructorId: "instructor-003",
    progress: 92,
    currentLesson: 24,
    joined: "2025-12-01",
    location: { city: "Kabala West", lat: 10.5166, lng: 7.4208 },
  },
];

export const initialInstructors = [
  {
    id: "instructor-001",
    name: "Pastor John Adamu",
    email: "john.adamu@example.com",
    whatsapp: "+234 803 111 2201",
    status: "Active",
    approval: "Approved",
    maxLoad: 8,
    unmarked: 4,
    graduationRequests: 0,
  },
  {
    id: "instructor-002",
    name: "Mrs. Blessing Okoro",
    email: "blessing.okoro@example.com",
    whatsapp: "+234 806 224 5190",
    status: "Active",
    approval: "Approved",
    maxLoad: 6,
    unmarked: 7,
    graduationRequests: 1,
  },
  {
    id: "instructor-003",
    name: "Elder David Ishaya",
    email: "david.ishaya@example.com",
    whatsapp: "+234 810 778 1042",
    status: "Active",
    approval: "Approved",
    maxLoad: 10,
    unmarked: 2,
    graduationRequests: 2,
  },
  {
    id: "instructor-004",
    name: "Sarah Emmanuel",
    email: "sarah.emmanuel@example.com",
    whatsapp: "+234 703 882 9181",
    status: "Active",
    approval: "Approved",
    maxLoad: 5,
    unmarked: 5,
    graduationRequests: 0,
  },
  {
    id: "instructor-005",
    name: "Andrew Bala",
    email: "andrew.bala@example.com",
    whatsapp: "+234 809 554 0032",
    status: "Inactive",
    approval: "Approved",
    maxLoad: 4,
    unmarked: 0,
    graduationRequests: 0,
  },
  {
    id: "instructor-006",
    name: "Mercy Danjuma",
    email: "mercy.danjuma@example.com",
    whatsapp: "+234 812 401 8860",
    status: "Pending",
    approval: "Awaiting Approval",
    maxLoad: 5,
    unmarked: 0,
    graduationRequests: 0,
  },
];

export const initialLessons = Array.from({ length: 26 }, (_, index) => ({
  id: `lesson-${String(index + 1).padStart(2, "0")}`,
  number: index + 1,
  title: [
    "We Can Believe in God",
    "We Can Believe the Bible",
    "Does My Life Really Matter to God?",
    "God's Plan for My Life",
    "The Bridge to a Satisfying Life",
    "A Second Chance at Life",
    "About Your Future",
    "When Jesus Comes for You",
    "Your Home in Heaven",
    "How Soon Will Jesus Return?",
    "Mysterious Power in My Life",
    "An Ever-Present Saviour",
    "From Guilty Sinner to Forgiven Saint",
    "The Secret of Answered Prayer",
    "The Secret of Happiness",
    "The Secret of Heavenly Rest",
    "The Secret of Growth Through Sharing",
    "The Secret of a Healthy Lifestyle",
    "Entering the Christian Life",
    "The Secret of Growth Through Fellowship",
    "Can the Majority Be Wrong?",
    "Is God Fair?",
    "What and Where Is Hell?",
    "When a Person Dies... What Then?",
    "Can I Find God's Church Today?",
    "Does God Have a Special Message for Our Day?",
  ][index],
  status: index < 4 ? "Uploaded" : "Not uploaded",
  fileName: index < 4 ? `lesson-${String(index + 1).padStart(2, "0")}.pdf` : "",
  uploadedAt: index < 4 ? "2026-06-10" : "",
}));

export const initialQuestions = [
  {
    id: "question-001",
    lesson: 1,
    order: 1,
    type: "Multiple choice",
    marker: "Auto-mark",
    prompt: "What is the central evidence that God exists?",
  },
  {
    id: "question-002",
    lesson: 1,
    order: 2,
    type: "Short answer",
    marker: "Pastor John Adamu",
    prompt: "Describe one way you have experienced God's care.",
  },
  {
    id: "question-003",
    lesson: 2,
    order: 1,
    type: "True or false",
    marker: "Auto-mark",
    prompt: "The Bible presents one connected story of redemption.",
  },
];

export const initialCertificates = [
  {
    id: "certificate-001",
    studentId: "student-005",
    code: "DBS-KD-CERT-26001",
    issuedAt: "2026-05-18",
    status: "Verified",
  },
  {
    id: "certificate-002",
    studentId: "student-010",
    code: "DBS-KD-CERT-26002",
    issuedAt: "2026-06-02",
    status: "Verified",
  },
];

export const initialNews = [
  {
    id: "news-001",
    title: "June graduation preparation",
    body: "Graduating students should confirm their names and certificate details.",
    mediaType: "Text",
    mediaName: "",
    status: "Published",
    publishedAt: "2026-06-08",
  },
];

export const createInitialAdminData = () => ({
  students: initialStudents,
  instructors: initialInstructors,
  lessons: initialLessons,
  questions: initialQuestions,
  certificates: initialCertificates,
  news: initialNews,
});
